#!/bin/bash

set -x
set -e

env

apt-get update
apt-get -y -q install apt-transport-https locales

echo "deb [trusted=yes] $APT ${DIST%%-*} main" > /etc/apt/sources.list.d/local.list
if [[ "${DIST##*-}" == "updates" ]] || [[ "${DIST##*-}" == "staging" ]]; then
  echo "deb [trusted=yes] $APT $DIST main" >> /etc/apt/sources.list.d/local.list
fi

apt-get update
apt-get -y -q install appbuild-essential

export PACKAGE=havis-apps

mkapp
